Add files via upload
# Whole idea is to make multiple vectors of dataset[] kept in asset folder by training it several times on mobile device.
# Working dataset and training code but :-< unable to produce word2vec output.
# Similar code tried on other (mobile) devices and worked perfectly fine. 
# Possible that dataset is not prepared correctly

#Error Discussion : https://gitter.im/deeplearning4j/deeplearning4j/archives/2016/09/06  

#Error1
  java.lang.IllegalStateException: You can't fit() model with empty Vocabulary or WeightLookupTable
        at org.deeplearning4j.models.sequencevectors.SequenceVectors.fit(SequenceVectors.java:238)
        at com.example.vijay.ondevice_word2vector.WordVectorTraining.trainW2V(WordVectorTraining.java:174)
        at com.example.vijay.ondevice_word2vector.MainActivity$1.run(MainActivity.java:50)
        at java.lang.Thread.run(Thread.java:764)
#Error2		
		2019-02-02 21:17:14.890 30303-30303/? A/DEBUG: pid: 30179, tid: 30284, name: VectorCalculati  >>> com.example.vijay.ondevice_word2vector <<<
2019-02-02 21:17:14.890 30303-30303/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
2019-02-02 21:17:14.890 30303-30303/? A/DEBUG: Cause: null pointer dereference
2019-02-02 21:17:14.890 30303-30303/? A/DEBUG:     r0 00000000  r1 00000000  r2 00000001  r3 00000000
2019-02-02 21:17:14.890 30303-30303/? A/DEBUG:     r4 00000000  r5 00000064  r6 00000000  r7 dc0212b8
2019-02-02 21:17:14.890 30303-30303/? A/DEBUG:     r8 00000000  r9 00000000  sl 00000064  fp b15f9450
2019-02-02 21:17:14.890 30303-30303/? A/DEBUG:     ip 00000001  sp b15f93d0  lr b21f1800  pc b7f5ca24  cpsr 200e0010

#  Code to check into